spring:
  application:
    name: Sanyu Scheduling App
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/free
    username: APP_AGEND_UT
    password: oracle
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: validate
  security:
    user:
      name: admin
      password: 12345

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /api/doc/swagger-ui

logging:
  level:
    org.springframework.security: DEBUG