spring:
  application:
    name: Sanyu Scheduling App
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/free
    username: APP_AGEND_UT
    password: oracle
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: validate

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /api/doc/swagger-ui

jwt:
  secret-key: 4d09f09234bfeb36d04306763a1d2880389c279ff37d12db00efd69f52cb24b2
  expiration-time: 86400000

frontend:
  url: http://localhost:4200

holiday-api:
  url: https://date.nager.at

mailjet:
  api-key: d970b8fb7805640ba9f8d97b8b0c38fe
  secret-key: 9e8da508475558bde9a1cce48c411fec
  from-email: ruiz100509@gmail.com

logging:
  level:
    org.springframework.security: DEBUG